### ISSUE TITLE
Question: TFS 2015 Compatibility

### ISSUE THREAD

**Issue by TheFellow** [Vaccano/TFS-Aggregator#11]
We're running TFS 2013 right now, and considering TFS Aggregator to implement some aggregate state transitions.

At the same time, we would like to move to TFS 2015 once it becomes available, but this then would require TFS Aggregator to work with 2015.

Do you guys have any idea if this plugin will function on 2015, or is it too early to tell?

**Comment by giuliov** [comment]
I am focusing my efforts on v2 located at https://github.com/tfsaggregator/tfsaggregator, it will support 2015 also. 90% we will not have enough bandwidth to validate the older version.
