### ISSUE TITLE
Adding New Link Types

### ISSUE THREAD

**Issue by O2mike0** [Vaccano/TFS-Aggregator#14]
How hard do you think it would be to modify the tool in order to use the Implements and Implemented By relationship on top of the already present Parent and Child relationship?

**Comment by giuliov** [comment]
We are writing v2 to solve this and more scenarios: you will have the full power of a scripting language to navigate relationship; it also offers some helpers (see [Fluent Queries](https://github.com/tfsaggregator/tfsaggregator/blob/master/docs/Scripting.md#fluent-queries)).

The new version is available at https://github.com/tfsaggregator/tfsaggregator. On the next release, I will switch all the links to the new site.
