### ISSUE TITLE
Trigger an aggregator rule on previously closed work items

### ISSUE THREAD

**Issue by einar20** [Vaccano/TFS-Aggregator#21]
I have created different aggregator scripts, that updates information in other linked work items.
My scripts works fine, and does their magic.

However, the updates performed, off course only applies to those work items saved after I created these scripts and customizations to wit's. Work items created earlier, does not have these aggregated information.

Is there a way to trigger an aggregator rule on previously closed work items, without opening them and save?

I could off course use the console app on server, but as far as I have understood, I would then have to peform these action on the work items one by one. Having approx 250 parent items created before the aggregator scripts were installed, that is not a very tempting task to start on :)

**Comment by giuliov** [comment]
@einar20 I suspect you are referring to Aggregator v2 (reference to Console app). In this case you should open the issue at https://github.com/tfsaggregator/tfsaggregator.

**Comment by einar20** [comment]
Sorry, for posting in the wrong repository. I'll Close this and move to the correct place
